name: responsive_ui_framework
description: A responsive UI framework for LG webOS applications with support for multiple aspect ratios, focus management, accessibility, and touch input.
version: 1.0.0
homepage: https://github.com/kevinseo2/Responsive_UI_Framework

environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
